### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA
ㄱㄱ
###jklj
jkwwwwwwwwwww
hjukh
hjkh
hkj
432
23
3
2r
HTTP2-Settings: r
w
rew
re
ww
r
w
rw
ㄴㅇㅇㅇㅇㅇ